
LUNA16ANNOTATIONPATH="/home/liubo/data/LUNA16/"  # 标签
DOWNLOADLUNA16PATH="/home/liubo/data/LUNA16/"   # 图片
LUNA16SEGMENTATIONPATH = "/home/liubo/data/LUNA16/" #分割
LUNA16PROCESSPATH="/home/liubo/data/LUNA16_PROCESS/" # 处理结果


config = {'train_data_path':[
                             DOWNLOADLUNA16PATH+'/subset0/',    # 训练路径  
                             DOWNLOADLUNA16PATH+'/subset1/',
                             DOWNLOADLUNA16PATH+'/subset2/', 
                             DOWNLOADLUNA16PATH+'/subset3/',
                             DOWNLOADLUNA16PATH+'/subset4/',
                             DOWNLOADLUNA16PATH+'/subset5/',
                             DOWNLOADLUNA16PATH+'/subset6/',
                             DOWNLOADLUNA16PATH+'/subset7/',
                             DOWNLOADLUNA16PATH+'/subset8/'],
          'val_data_path':[DOWNLOADLUNA16PATH+'/subset9/'],     # 验证数据路径
          'test_data_path':[DOWNLOADLUNA16PATH+'/subset9/'],    # 测试数据路径
          
          'train_preprocess_result_path':LUNA16PROCESSPATH, # contains numpy for the data and label, which is generated by prepare.py   # numpy 格式的训练数据和标签
          'val_preprocess_result_path':LUNA16PROCESSPATH,  # make sure copy all the numpy into one folder after prepare.py     # numpy 格式的验证数据和标签
          'test_preprocess_result_path':LUNA16PROCESSPATH,     # numpy 格式的测试数据和标签
          
          'train_annos_path':LUNA16ANNOTATIONPATH+'/CSVFILES/annotations.csv',
          'val_annos_path':LUNA16ANNOTATIONPATH+'/CSVFILES/annotations.csv',
          'test_annos_path':LUNA16ANNOTATIONPATH+'/CSVFILES/annotations.csv',

          'black_list':[],   # 处理的黑名单
          
          'preprocessing_backend':'python',  

          'luna_segment':LUNA16SEGMENTATIONPATH+'/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':LUNA16PROCESSPATH,
          'luna_data':DOWNLOADLUNA16PATH,
          'luna_label':LUNA16ANNOTATIONPATH+'/CSVFILES/annotations.csv'
         } 
