

"""
LUNA16 数据说明（来自：https://luna16.grand-challenge.org/Data/）
subset0.zip to subset9.zip: 10 zip files which contain all CT images
annotations.csv: csv file that contains the annotations used as reference standard for the 'nodule detection' track
sampleSubmission.csv: an example of a submission file in the correct format
candidates.csv: the original set of candidates used for the LUNA16 workshop at ISBI2016. This file is kept for completeness, but should not be used, use candidates_V2.csv instead (see more info below).
candidates_V2.csv: csv file that contains an extended set of candidate locations for the ‘false positive reduction’ track. 
evaluation script: the evaluation script that is used in the LUNA16 framework
lung segmentation: a directory that contains the lung segmentation for CT images computed using automatic algorithms
additional_annotations.csv: csv file that contain additional nodule annotations from our observer study. The file will be available soon
"""

LUNA16ROOTPATH="/home/liubo/data/LUNA16/"  # 原来的数据集跟目录
LUNA16PROCESSPATH="/home/liubo/data/LUNA16_PROCESS_NEW/" # 处理结果


config = {'luna_root':LUNA16ROOTPATH,
          'train_data_path':[
                             LUNA16ROOTPATH+'/subset0/',    # 训练路径  
                             LUNA16ROOTPATH+'/subset1/',
                             LUNA16ROOTPATH+'/subset2/', 
                             LUNA16ROOTPATH+'/subset3/',
                             LUNA16ROOTPATH+'/subset4/',
                             LUNA16ROOTPATH+'/subset5/',
                             LUNA16ROOTPATH+'/subset6/',
                             LUNA16ROOTPATH+'/subset7/',
                             LUNA16ROOTPATH+'/subset8/'],
          #测试和验证现在是一个数据集
          'val_data_path':  [LUNA16ROOTPATH+'/subset9/'],     # 验证数据路径
          'test_data_path': [LUNA16ROOTPATH+'/subset9/'],    # 测试数据路径
          
          # 现在这三份的路径一样
          'train_preprocess_result_path':LUNA16PROCESSPATH, # contains numpy for the data and label, which is generated by prepare.py   也就是处理结果
          'val_preprocess_result_path':LUNA16PROCESSPATH,  # make sure copy all the numpy into one folder after prepare.py     # numpy 格式的验证数据和标签
          'test_preprocess_result_path':LUNA16PROCESSPATH,   
          
          # annotations.csv 相当于label
          'train_annos_path':LUNA16ROOTPATH+'/CSVFILES/annotations.csv',
          'val_annos_path':LUNA16ROOTPATH+'/CSVFILES/annotations.csv',
          'test_annos_path':LUNA16ROOTPATH+'/CSVFILES/annotations.csv',

          'black_list':[],   # 处理的黑名单
          
          'preprocessing_backend':'python',  

          'luna_segment':LUNA16ROOTPATH+'/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':LUNA16PROCESSPATH,
          'luna_label':LUNA16ROOTPATH+'/CSVFILES/annotations.csv'
         } 
